version: "3.7"
services:
  task_service:
    image: "task_api"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: task_service_db
      MYSQL_ROOT_PASSWORD: root